version: '3'
services:
  nginx:
    container_name: some-nginx
    image: nginx:1.13
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - login
      - shop
      - images
  login:
    restart: always
    image: vdwps/cmd-benchmarking-app:1.0.0
    ports:
      - "8080:8080"
    environment:
      - "endpoint=login"
      - "delay=300"
      - "response=you've logged in "
  shop:
    restart: always
    image: vdwps/cmd-benchmarking-app:1.0.0
    ports:
      - "8081:8080"
    environment:
      - "endpoint=shop"
      - "delay=500"
      - 'response={"teas": [{"product-name": "Earl Grey (loose)", "price": "4,20"}, {"product-name": "Darjeeling (loose)", "price": "6,90"}]}'
      - "responseType=json"
  images:
    restart: always
    image: vdwps/cmd-benchmarking-app:1.0.0
    ports:
      - "8082:8080"
    environment:
      - "endpoint=images"
      - "response=reached images. # of calls: "
      - "appendAmountOfCallsToResponse=true"
      - "logging.level.tech.dobler=DEBUG"
  shop1:
    restart: always
    image: vdwps/cmd-benchmarking-app:1.0.0
    ports:
      - "8083:8080"
    environment:
      - "endpoint=shop/1"
      - 'response={"product-name": "Earl Grey (loose)", "price": "4,20"}'
      - "responseType=json"
  landingpage:
    restart: always
    image: vdwps/cmd-benchmarking-app:1.0.0
    ports:
      - "8084:8080"
    environment:
      - "endpoint=index"
      - "logging.level.tech.dobler=DEBUG"
      - "forwardCall=http://images:8080/images/"
      - "appendParamToResponse=false"